### ISSUE TITLE
Fix bounding box move twice

### ISSUE THREAD

**Issue by GuillaumeLazar** [neuronalmotion/blueprint#28]
Fixing this issue should help with the current bounding box implementation and avoid that: 
![snapshot1](https://cloud.githubusercontent.com/assets/7305456/8844208/9fbda870-3112-11e5-8fb7-fff68e886457.png)

**Comment by GuillaumeLazar** [comment]
@synapticvoid, the description is ok for you?

**Comment by synapticvoid** [comment]
Perfect!
