### ISSUE TITLE
Display multiple Sketches (CanvasView) in the MainWindow

### ISSUE THREAD

**Issue by synapticvoid** [neuronalmotion/blueprint#33]
Right now a single Sketch is visible.

**Comment by GuillaumeLazar** [comment]
It's how Sketch 3, display multiple "sketches" on the same view

![hero-screenshot](https://cloud.githubusercontent.com/assets/7305456/9243255/881bc3fa-418e-11e5-9ab4-3fa24bb535db.png)

**Comment by GuillaumeLazar** [comment]
Some useful resources about Sketch 3 "page and art board" : 

[![IMAGE ALT TEXT HERE](http://img.youtube.com/vi/A-0xWk6BFq4/0.jpg)](http://www.youtube.com/watch?v=A-0xWk6BFq4)

[![IMAGE ALT TEXT HERE](http://img.youtube.com/vi/b3vBZvGxZo0/0.jpg)](http://www.youtube.com/watch?v=b3vBZvGxZo0)

OK that's my sum up  of these videos:

General structure is  : 
- Project
  - Pages
    - Artboards
      - Shapes

About page : 
- Only one page is displayed at the same time

About artboard : 
- This is what you export to a picture (PNG, ...)
- Different sizes on the same page are allowed
- Size can be changed after creation
- Pre configured size are proposed

About shapes : 
- contained by an artboard
- partially visible if out of bounds of artboard
- can be transfer to another artboard by drag & drop

**Comment by GuillaumeLazar** [comment]
Blueprint got similar project structure:

| Sketch 3 | Blueprint |
| --- | --- |
| Page | Page |
| Artboard | Sketch |
| Shape | SketchItem |

I think that our "Sketch" is a little tricky and doesn't represent the "collection" spirit.
What do you think about use "Canvas" word (even YT Sketch3 video use this term to talk about artboard)

And maybe "SketchItem" could become just "Item" ?

@synapticvoid  what do think about that?

**Comment by synapticvoid** [comment]
Yup, I like Canvas.

About SketchItem, I think that Shape might be better, Item is really too generic in my opinion.

**Comment by GuillaumeLazar** [comment]
Yea ok for me. Shape is better and is not a Sketch3 word reserved! :rage: 

| Sketch 3 | Blueprint |
| --- | --- |
| Page | Page |
| Artboard | Canvas |
| Shape | Shape |

I will perform some refactoring in code to respect that new naming convention.
SketchItem -> Shape
SketchItemBezier -> ShapeBezier
SketchItemEllipse -> ShapeEllipse
[...]
