### ISSUE TITLE
Resize CircleSketchItem using the bounding box

### ISSUE THREAD

**Issue by synapticvoid** [neuronalmotion/blueprint#7]

**Comment by GuillaumeLazar** [comment]
Resize a rectangle is quite easy. This one could be more complex.

E.g : If I move the top BB's handle to the top, I want that the top bezier move top.... but not only this one. I guess we should move left and right bezier handles too. May be half of the delta?

**Comment by synapticvoid** [comment]
Yep I think you're right, you should also move the bezier control point. As you said, moving it half the distance seems a sound decision.

**Comment by synapticvoid** [comment]
Thinking about it, we might have to do the same for the rectangle!

**Comment by synapticvoid** [comment]
Using a matrix transformation might do the trick, it seems to be available in our `QGraphicsItem` => http://doc.qt.io/qt-5/qgraphicsitem.html#setTransform .

As a reminder: https://en.wikipedia.org/wiki/Scaling_(geometry)

**Comment by GuillaumeLazar** [comment]
I tried setTransform() and associated object QTransform, it's not what we want. That applies a scale to all item properties and all children. Event graphics border are scaled :disappointed: . That quite ugly.

I propose for the milestone to perform a specific resize (as we have with rectangle). And after refactor it implementing a "Universal bezier bounding box" #38

**Comment by synapticvoid** [comment]
Okay, let's go for it step by step
