### ISSUE TITLE
Draw a SketchItemRectangle

### ISSUE THREAD

**Issue by synapticvoid** [neuronalmotion/blueprint#8]

**Comment by GuillaumeLazar** [comment]
Should we use bezier points to draw it or only classic rectangle item for now?

Maybe each item could have two edit modes: 
- classic : with witdth/height resize (only display main items points)
- bezier : with bezier deformation (display bezier control points)

I think that display bezier points each time for just to change the width of an item could be a little bit complicated to a simple task?

@synapticvoid What is your point on that?

**Comment by synapticvoid** [comment]
Yup, good idea, we could use a key modifier (ctrl / alt) to switch between normal/bezier mode.
